/**
 * Sync public Google Drive folders into src/galleryDriveItems.generated.js
 * Uses embedded folderview (no API key). Re-run after adding photos to Drive:
 *   npm run sync-drive-gallery
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "src", "galleryDriveItems.generated.js");

const FOLDERS = {
  "phong-su": "1kIn80ySGz2Rbq4JX2chgUwlyPTZfqUuV",
  "truyen-thong": "1AH_To1HH-WY6lVo1eVxm5K3kVqNV5rga",
};

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": "save-the-date-gallery-sync/1.0" } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          fetchText(res.headers.location).then(resolve).catch(reject);
          return;
        }
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} for ${url}`));
          return;
        }
        let data = "";
        res.on("data", (chunk) => {
          data += chunk;
        });
        res.on("end", () => resolve(data));
      })
      .on("error", reject);
  });
}

function decodeHtml(text) {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}

function parseFolderHtml(html) {
  const items = [];
  const seen = new Set();
  const entryRe =
    /class="flip-entry" id="entry-([^"]+)"[\s\S]*?href="https:\/\/drive\.google\.com\/file\/d\/([^/]+)\/view[^"]*"[\s\S]*?alt="([^"]*)"/g;
  let m;
  while ((m = entryRe.exec(html)) !== null) {
    const fileId = m[2] || m[1];
    if (!fileId || seen.has(fileId)) continue;
    seen.add(fileId);
    const alt = decodeHtml(m[3] || "").trim();
    items.push({
      fileId,
      alt: alt && !/^jpe?g image$/i.test(alt) ? alt : `Photo ${items.length + 1}`,
    });
  }

  if (items.length === 0) {
    const fallbackRe = /\/file\/d\/([a-zA-Z0-9_-]+)\/view/g;
    while ((m = fallbackRe.exec(html)) !== null) {
      const fileId = m[1];
      if (seen.has(fileId)) continue;
      seen.add(fileId);
      items.push({ fileId, alt: `Photo ${items.length + 1}` });
    }
  }

  return items;
}

async function syncFolder(categoryId, folderId) {
  const url = `https://drive.google.com/embeddedfolderview?id=${encodeURIComponent(folderId)}`;
  const html = await fetchText(url);
  const items = parseFolderHtml(html);
  if (items.length === 0) {
    throw new Error(`No files found in folder ${categoryId} (${folderId}). Is the folder shared publicly?`);
  }
  console.log(`  ${categoryId}: ${items.length} file(s)`);
  return items;
}

async function main() {
  console.log("Syncing Google Drive gallery folders...\n");
  const result = {};

  for (const [categoryId, folderId] of Object.entries(FOLDERS)) {
    result[categoryId] = await syncFolder(categoryId, folderId);
  }

  const body = `/** Auto-generated by scripts/syncDriveGallery.cjs — do not edit manually */
export const GALLERY_DRIVE_FOLDER_IDS = ${JSON.stringify(FOLDERS, null, 2)};

export const GALLERY_DRIVE_ITEMS = ${JSON.stringify(result, null, 2)};
`;

  fs.writeFileSync(OUT, body, "utf8");
  console.log(`\nWrote ${OUT}`);
}

main().catch((err) => {
  console.error(err.message || err);
  process.exit(1);
});
